name: Swift CI

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  build:
    name: Build
    runs-on: macos-13
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_14.3.app

      - name: Build Project
        run: |
          xcodebuild -scheme Farmart \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 14' \
                     clean build | xcpretty

  test:
    name: Run Unit Tests
    runs-on: macos-13
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_14.3.app

      - name: Run Tests
        run: |
          xcodebuild -scheme Farmart \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 14' \
                     clean test | xcpretty

  lint:
    name: SwiftLint           # ✅ optional, no branch rule expecting this
    runs-on: macos-13
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint
